/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacio2;

import java.awt.Color;

/**
 *
 * @author Ernesto
 */
public class frameMENU extends javax.swing.JFrame {

    /**
     * Creates new form frameMENU
     */
    public frameMENU() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        this.getContentPane().setBackground(Color.ORANGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnguia1 = new javax.swing.JButton();
        btnguia2 = new javax.swing.JButton();
        btnguia3y4 = new javax.swing.JButton();
        btnteoria = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("¿QUE DESEA REALIZAR?");

        btnguia1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguia1.setText("GUIA 1");
        btnguia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguia1ActionPerformed(evt);
            }
        });

        btnguia2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguia2.setText("GUIA 2");
        btnguia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguia2ActionPerformed(evt);
            }
        });

        btnguia3y4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguia3y4.setText("GUIA 3 Y 4");
        btnguia3y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguia3y4ActionPerformed(evt);
            }
        });

        btnteoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnteoria.setText("TEORIA");
        btnteoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnteoriaActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguia2)
                    .addComponent(btnteoria))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnguia3y4)
                            .addComponent(btnguia1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnsalir)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(btnguia1)
                .addGap(17, 17, 17)
                .addComponent(btnguia2)
                .addGap(19, 19, 19)
                .addComponent(btnguia3y4)
                .addGap(21, 21, 21)
                .addComponent(btnteoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguia1ActionPerformed
        
        FrameGuia1 uno=new FrameGuia1();
        uno.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnguia1ActionPerformed

    private void btnguia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguia2ActionPerformed
        frameGuia2 dos=new frameGuia2();
        dos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnguia2ActionPerformed

    private void btnguia3y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguia3y4ActionPerformed
        frameGuia3 tres=new frameGuia3();
        tres.setVisible(true);
    }//GEN-LAST:event_btnguia3y4ActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnteoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnteoriaActionPerformed
        
        frameTeoria cuatro=new frameTeoria();
        cuatro.setVisible(true);
        
    }//GEN-LAST:event_btnteoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguia1;
    private javax.swing.JButton btnguia2;
    private javax.swing.JButton btnguia3y4;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnteoria;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
