/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacio2;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ernesto
 */
public class frameGuia3 extends javax.swing.JFrame {
    int dato = 0, bat = 0, pixP = 0, pixF = 0, dato9 = 0;
    double dato2 = 0, dato4 = 0, dato7 = 0;
    String dato1 = "", dato3 = "", dato5 = "", dato6 = "", dato8 = "", marca;

    /**
     * Creates new form frameGuia3
     */
    public frameGuia3() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        
        this.getContentPane().setBackground(Color.MAGENTA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtCpu = new javax.swing.JTextField();
        jtRam = new javax.swing.JTextField();
        jtTam1 = new javax.swing.JTextField();
        jtGarantia = new javax.swing.JTextField();
        cmbMarca = new javax.swing.JComboBox<String>();
        rbtnPrincipal = new javax.swing.JRadioButton();
        rbtnSecundaria = new javax.swing.JRadioButton();
        rbtnFlash = new javax.swing.JRadioButton();
        btnEjecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtCampo = new javax.swing.JTextArea();
        txtPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Cantidad de ram");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tiempo de garantia");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Precio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Marca");

        jtCpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCpuActionPerformed(evt);
            }
        });
        jtCpu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCpuKeyTyped(evt);
            }
        });

        jtRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRamActionPerformed(evt);
            }
        });
        jtRam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtRamKeyTyped(evt);
            }
        });

        jtTam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTam1ActionPerformed(evt);
            }
        });
        jtTam1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtTam1KeyTyped(evt);
            }
        });

        jtGarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtGarantiaActionPerformed(evt);
            }
        });
        jtGarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtGarantiaKeyTyped(evt);
            }
        });

        cmbMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SAMSUNG", "IPhone", "Nokia", "Alcatel", "HUAWEI", "SONY", "Otro" }));
        cmbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarcaActionPerformed(evt);
            }
        });

        rbtnPrincipal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnPrincipal.setText("Principal");

        rbtnSecundaria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnSecundaria.setText("Secundaria");

        rbtnFlash.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnFlash.setText("Flash");

        btnEjecutar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEjecutar.setText("EJECUTAR");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        jtxtCampo.setEditable(false);
        jtxtCampo.setColumns(20);
        jtxtCampo.setRows(5);
        jScrollPane1.setViewportView(jtxtCampo);

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Camaras:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CPU numero de nucleos");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("PUNTAJE DE MOVILES");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tamaño de pantallas");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtRam, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtTam1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(rbtnPrincipal)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnSecundaria)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnFlash))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnEjecutar)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtTam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnPrincipal)
                        .addComponent(rbtnSecundaria)
                        .addComponent(rbtnFlash))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnEjecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCpuActionPerformed

    }//GEN-LAST:event_jtCpuActionPerformed

    private void jtCpuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCpuKeyTyped
        char k = evt.getKeyChar();

        dato5 = dato5 + k;
        dato = Integer.parseInt(dato5);

        if (dato > 12) {
            JOptionPane.showMessageDialog(null, "NO se permite ingreso mayor a 12");
            jtCpu.setText(null);
            evt.consume();
            dato = 0;
            dato5 = "";
        }

        if(k<'0' || k>'9'){

            evt.consume();
        }
        int limite=2;
        if(jtCpu.getText().length()==limite){
            evt.consume();
        }

    }//GEN-LAST:event_jtCpuKeyTyped

    private void jtRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRamActionPerformed

    private void jtRamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRamKeyTyped

        char k = evt.getKeyChar();

        dato3 = dato3 + k;
        dato4 = Double.parseDouble(dato3);

        if (dato4 < 0.5 || dato4 > 6.0) {
            JOptionPane.showMessageDialog(null, "NO se permite ingreso mayor a 6.0 ni menor a 0.5");
            jtRam.setText(null);
            evt.consume();
            dato4 = 0;
            dato3 = "";
        }

        if ((k < '0' || k > '9') && k != '.') {
            evt.consume();

        }
        int limite = 3;
        if (jtRam.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_jtRamKeyTyped

    private void jtTam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTam1ActionPerformed

    private void jtTam1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTam1KeyTyped
        char k = evt.getKeyChar();

        dato1 = dato1 + k;
        dato2 = Double.parseDouble(dato1);

        if (dato2 < 3.0 || dato2 > 6.7) {
            JOptionPane.showMessageDialog(null, "NO se permite ingreso mayor a 6.7 ni menor a 3.0");
            jtTam1.setText(null);
            evt.consume();
            dato2 = 0;
            dato1 = "";
        }

        if ((k < '0' || k > '9') && k != '.') {
            evt.consume();

        }
        int limite = 3;
        if (jtTam1.getText().length() == limite) {
            evt.consume();

        }
    }//GEN-LAST:event_jtTam1KeyTyped

    private void jtGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtGarantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtGarantiaActionPerformed

    private void jtGarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtGarantiaKeyTyped

        char k=evt.getKeyChar();

        dato6=dato6+k;
        dato9=Integer.parseInt(dato6);
        if(dato9>24){
            JOptionPane.showMessageDialog(null,"NO se permite ingreso mayor a 24");
            jtGarantia.setText(null);
            evt.consume();
            dato9=0;
            dato6="";
        }

        if(k<'0' || k>'9'){

            evt.consume();

        }
        int limite=2;
        if(jtGarantia.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jtGarantiaKeyTyped

    private void cmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMarcaActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        /*  meto.BateriaPantalla();
        meto.Pixelaje();
        meto.cpu();
        meto.garantia();
        meto.suma();
        meto.ram();
        meto.rangoPrecio();
        meto.refDeMarca();*/

        String camara="";
        marca=String.valueOf((cmbMarca.getSelectedItem()));
        // pixP=Integer.parseInt(String.valueOf(txtMegapixeles));

        if(rbtnFlash.isSelected()){
            camara=camara+"Flash ";
        }
        if(rbtnPrincipal.isSelected()){
            camara=camara+"Principal ";
        } if(rbtnSecundaria.isSelected()){
            camara=camara+"Secundaria ";
        }

        jtxtCampo.setText("El numero del CPU es:"+dato+"\n"+"El tamaño de la pantalla es:"+dato2+"\n"+
            "La cantidad de RAM es:"+dato4+"\n"+"El numero de garantia es:"+dato6+" meses\n"+"El precio es de: $"+txtPrecio.getText()+"\n"+"Marca:"+cmbMarca.getSelectedItem()+"\n");

    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char k=evt.getKeyChar();

        dato8=dato8+k;
        dato7=Double.parseDouble(dato8);

        if(dato7<0.01 || dato7>999.99){
            JOptionPane.showMessageDialog(null,"NO se permite ingreso mayor a 999.99 ni menor a 0.01");
            txtPrecio.setText(null);
            evt.consume();
            dato7=0;
            dato8="";
        }

        if((k<'0' || k>'9') && k!='.'){
            evt.consume();

        }
        int limite=6;
        if(txtPrecio.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameGuia3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameGuia3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameGuia3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameGuia3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameGuia3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtCpu;
    private javax.swing.JTextField jtGarantia;
    private javax.swing.JTextField jtRam;
    private javax.swing.JTextField jtTam1;
    private javax.swing.JTextArea jtxtCampo;
    private javax.swing.JRadioButton rbtnFlash;
    private javax.swing.JRadioButton rbtnPrincipal;
    private javax.swing.JRadioButton rbtnSecundaria;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
