/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacio2;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ernesto
 */
public class FrameGuia1 extends javax.swing.JFrame {

    /**
     * Creates new form FrameGuia1
     */
    public FrameGuia1() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        
        this.getContentPane().setBackground(Color.YELLOW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnArea = new javax.swing.JButton();
        btnCircunferencia = new javax.swing.JButton();
        btnEsfera = new javax.swing.JButton();
        btnCubo = new javax.swing.JButton();
        btnDatos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("¿QUE DESEA REALIZAR?");

        btnArea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnArea.setText("CALCULAR EL AREA Y DIAMETRO");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        btnCircunferencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCircunferencia.setText("CALCULAR CIRCUNFERENCIA");
        btnCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircunferenciaActionPerformed(evt);
            }
        });

        btnEsfera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEsfera.setText("CALCULAR EL VOLUMEN DE UNA ESFERA");
        btnEsfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsferaActionPerformed(evt);
            }
        });

        btnCubo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCubo.setText("CALCULAR EL VOLUMEN DE UN CUBO");
        btnCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuboActionPerformed(evt);
            }
        });

        btnDatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDatos.setText("CALCULAR EL PROMEDIO DE 10 DATOS");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnArea))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCircunferencia))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEsfera))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCubo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDatos)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnArea)
                .addGap(18, 18, 18)
                .addComponent(btnCircunferencia)
                .addGap(18, 18, 18)
                .addComponent(btnEsfera)
                .addGap(18, 18, 18)
                .addComponent(btnCubo)
                .addGap(18, 18, 18)
                .addComponent(btnDatos)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        
        double resultado=0,diagonal=0;
       
      
            double base=Double.parseDouble(JOptionPane.showInputDialog("Ingrese la base"));
            double altura=Double.parseDouble(JOptionPane.showInputDialog("Ingrese la altura"));
            
            resultado=base*altura;
            diagonal=Math.sqrt(Math.pow(base,2)+Math.pow(altura,2));
            
            
        JOptionPane.showMessageDialog(null,"El area es: " +resultado+ " La diagonal es: "+diagonal);
        
        
    
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircunferenciaActionPerformed
        
        double resultado=0;
        
        double radio=Double.parseDouble(JOptionPane.showInputDialog("Ingrese el radio de la circunferencia"));
        
        resultado=(3.14)*(radio*2);
        
        JOptionPane.showMessageDialog(null,"La circunferencia del circulo es: "+resultado);
    }//GEN-LAST:event_btnCircunferenciaActionPerformed

    private void btnEsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsferaActionPerformed
        
        double resultado=0;
        
        double radio=Double.parseDouble(JOptionPane.showInputDialog("Ingrese el radio de la esfera"));
        
        
        resultado=(4.18666)*(Math.pow(radio,3));
        
        JOptionPane.showMessageDialog(null,"El volumen de la esfera es: "+resultado);
    }//GEN-LAST:event_btnEsferaActionPerformed

    private void btnCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuboActionPerformed

        double resultado=0;
        
        double area=Double.parseDouble(JOptionPane.showInputDialog("Ingrese el area del cubo"));
        
        
        resultado=(Math.pow(area,3));
        
        JOptionPane.showMessageDialog(null,"El volumen del cubo es: "+resultado);
        
    }//GEN-LAST:event_btnCuboActionPerformed

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        
         double vector[]=new double[10];
        double suma=0,promedio=0;
        for(int i=0;i<10;i++){
            vector[i]=Double.parseDouble(JOptionPane.showInputDialog("Ingrese dato "+(i+1)));
            suma=suma+vector[i];
        }
        promedio=suma/10;
        
        JOptionPane.showMessageDialog(null,"El promedio de los datos ingresados es: "+promedio);
        
    }//GEN-LAST:event_btnDatosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        System.exit(0);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGuia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGuia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGuia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGuia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGuia1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnCircunferencia;
    private javax.swing.JButton btnCubo;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnEsfera;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
